filtering:
  exclude_training_words: true
  min_edit_distance: 2
  remove_duplicates: true
generation:
  ends_with: ''
  excludes: ''
  includes: ''
  max_length: 14
  max_time_per_name: 0.02
  min_length: 5
  n_words: 20
  regex_pattern: ''
  starts_with: ''
model:
  backoff: true
  order: 3
  prior: 0.01
output:
  format: list
  output_file: generated_names.txt
  save_to_file: false
  sort_ascending: true
  sort_by: length
training_data:
  combine_sources: true
  sources:
  - american_cities.txt
word_list_ratings:
  american_cities.txt: 0
  animal_sounds.txt: 4
  atomic_and_subatomic_particles.txt: 2
