filtering:
  exclude_training_words: true
  min_edit_distance: 2
  remove_duplicates: true
generation:
  ends_with: ''
  excludes: ''
  includes: ''
  max_length: 14
  max_time_per_name: 0.02
  min_length: 5
  n_words: 20
  regex_pattern: ''
  starts_with: ''
llm:
  default_instructions: Based on the provided description and scored names, score
    the following generated name ideas on a scale of 0.0 to 5.0, where 5.0 is excellent
    and 0.0 is poor. Consider factors like memorability, relevance, uniqueness, and
    overall appeal.
  max_chunk_size: 10
  model: gpt-3.5-turbo
model:
  backoff: true
  order: 3
  prior: 0.01
output:
  format: list
  output_file: generated_names.txt
  save_to_file: false
  sort_ascending: true
  sort_by: length
training_data:
  combine_sources: true
  sources:
  - animal_sounds.txt
  - atomic_and_subatomic_particles.txt
  - roman_emperor_forenames.txt
word_list_ratings:
  american_cities.txt: 0
  animal_sounds.txt: 4
  atomic_and_subatomic_particles.txt: 2
  programming_languages.txt: 2
  roman_deities.txt: 3
  roman_emperor_forenames.txt: 3
