ai_settings:
  max_names: 100
filtering:
  exclude_training_words: true
  min_edit_distance: 2
  remove_duplicates: true
generation:
  ends_with: mind
  excludes: ''
  includes: ''
  max_length: 12
  max_time_per_name: 3
  min_length: 6
  n_words: 200
  regex_pattern: ''
  starts_with: ''
llm:
  default_instructions: Based on the provided description and scored names, score
    the following generated name ideas on a scale of 0 to 5, where 5 is excellent
    and 0 is poor (use integer scores). Consider factors like memorability, relevance,
    uniqueness, and overall appeal. Reply with the scores as a JSON dict where keys
    are the actual name strings and values are the scores.
  description: We are going to evaluate names for an AI agent that acts as the collective
    mind for communities and organizations. This agent will embody the collective
    consciousness of the group, act as echochamber, brainstorming partner, collective
    memory and coordination agent for teams, communities, festivals and decentralized
    organisations. The name should feel welcoming, organic, meta, but also grand and
    present. Ideally, the name has some hints as to its purpose.
  max_chunk_size: 10
  model: gpt-5-mini
model:
  backoff: false
  order: 3
  temperature: 0.9
output:
  format: list
  output_file: generated_names.txt
  save_to_file: false
  sort_ascending: true
  sort_by: length
saved_ratings:
  aurick: 4
  auton: 3
  tenna: 3
training_data:
  combine_sources: true
  score_range:
    max: 5
    min: 2
  sources:
  - animal_sounds.txt
  - atomic_and_subatomic_particles.txt
  - egyptian_deities.txt
  - fabrics.txt
  - icelandic_forenames.txt
  - pokemon.txt
  - pokemon_modern.txt
  - programming_languages.txt
  - roman_deities.txt
  - roman_emperor_forenames.txt
  - roman_place_names.txt
  - satellites_natural.txt
  - swedish_forenames.txt
  - theological_angels.txt
  - theological_demons.txt
  - tolkienesque_forenames.txt
  - websites.txt
word_list_ratings:
  american_cities.txt: 0
  american_companies.txt: 0
  american_forenames.txt: 0
  animal_sounds.txt: 4
  atomic_and_subatomic_particles.txt: 2
  egyptian_deities.txt: 3
  fabrics.txt: 3
  icelandic_forenames.txt: 2
  pokemon.txt: 4
  pokemon_modern.txt: 4
  programming_languages.txt: 2
  roman_deities.txt: 3
  roman_emperor_forenames.txt: 3
  roman_place_names.txt: 2
  satellites_natural.txt: 3
  swedish_forenames.txt: 3
  theological_angels.txt: 4
  theological_demons.txt: 4
  tolkienesque_forenames.txt: 4
  websites.txt: 3
