config:
  filtering:
    exclude_training_words: true
    min_edit_distance: 2
    remove_duplicates: true
  generation:
    ends_with: ''
    excludes: ''
    includes: ''
    max_length: 9
    max_time_per_name: 0.02
    min_length: 5
    n_words: 100
    regex_pattern: ''
    starts_with: co
  llm:
    default_instructions: 'Based on the provided description and scored names, score
      the following generated name ideas on a scale of 0 to 5, where 5 is excellent
      and 0 is poor (use integer scores). Consider factors like memorability, relevance,
      uniqueness, and overall appeal. Reply with the scores as a JSON array of index:score
      (0 to 5), one for each name in order and nothing else. Example: [1:3, 2:4, 3:0,
      4:3]'
    max_chunk_size: 30
    model: gpt-4o-mini
  model:
    backoff: true
    order: 4
    prior: 0.01
  output:
    format: list
    output_file: generated_names.txt
    save_to_file: false
    sort_ascending: true
    sort_by: length
  saved_ratings: &id001
    aurick: 4
    auton: 3
    chatty: 1
    clark: 2
    crowzd: 3
    "flaea\xEB": 1
    liberyx: 2
    tenna: 3
  training_data:
    combine_sources: true
    sources:
    - american_cities.txt
    - animal_sounds.txt
    - atomic_and_subatomic_particles.txt
    - pokemon.txt
    - pokemon_modern.txt
    - programming_languages.txt
    - roman_deities.txt
    - roman_emperor_forenames.txt
    - roman_place_names.txt
    - theological_angels.txt
    - theological_demons.txt
    - tolkienesque_forenames.txt
    - websites.txt
  word_list_ratings: &id002
    american_cities.txt: 2
    american_companies.txt: 0
    american_forenames.txt: 0
    animal_sounds.txt: 4
    atomic_and_subatomic_particles.txt: 2
    pokemon.txt: 4
    pokemon_modern.txt: 4
    programming_languages.txt: 2
    roman_deities.txt: 3
    roman_emperor_forenames.txt: 3
    roman_place_names.txt: 2
    theological_angels.txt: 4
    theological_demons.txt: 4
    tolkienesque_forenames.txt: 4
    websites.txt: 3
gui_state:
  ai_chunk_size: 30
  ai_description: I need a name for my creative AI agent. This AI agent will be a
    collective mind, a coordinating brain that helps communities and groups of people
    organize events and construct collective narrative from decentralized activity.
    My first decent idea for a name was "CoMi" (from Collective Mind).
  ai_gen_count: 100
  ai_instructions: 'Based on the provided description and scored names, score the
    following generated name ideas on a scale of 0 to 5, where 5 is excellent and
    0 is poor (use integer scores). Consider factors like memorability, relevance,
    uniqueness, and overall appeal. Reply with the scores as a JSON array of index:score
    (0 to 5), one for each name in order and nothing else. Example: [1:3, 2:4, 3:0,
    4:3]'
  max_score: 5
  min_score: 1
saved_ratings: *id001
word_list_ratings: *id002
